
package Ventanas;


import Clases.Huesped;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;



public class vHuesped extends javax.swing.JFrame {

 ArrayList <Huesped> Hu;
    
    public vHuesped(ArrayList<Huesped>AHu) {
        Hu=AHu;
        initComponents();
        LeerBinarioHuesped();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eHuesped = new javax.swing.JLabel();
        eHuespedT = new javax.swing.JLabel();
        bSalir2 = new javax.swing.JButton();
        eCodigo = new javax.swing.JLabel();
        tCodigo = new javax.swing.JTextField();
        eNombre = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        tCorreo = new javax.swing.JTextField();
        eCorreo = new javax.swing.JLabel();
        eTelefono = new javax.swing.JLabel();
        tTelefono = new javax.swing.JTextField();
        eNit = new javax.swing.JLabel();
        tNit = new javax.swing.JTextField();
        bBuscar = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        bBinario = new javax.swing.JButton();
        bAgregar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        eHuesped.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO F.png"))); // NOI18N

        eHuespedT.setFont(new java.awt.Font("Bahnschrift", 1, 45)); // NOI18N
        eHuespedT.setText("HUESPEDES");

        bSalir2.setBackground(new java.awt.Color(204, 204, 204));
        bSalir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SALIR.png"))); // NOI18N
        bSalir2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        bSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalir2ActionPerformed(evt);
            }
        });

        eCodigo.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        eCodigo.setText("CODIGO");

        tCodigo.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        tCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        eNombre.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        eNombre.setText("NOMBRE");

        tNombre.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        tNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tCorreo.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        tCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        eCorreo.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        eCorreo.setText("CORREO");

        eTelefono.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        eTelefono.setText("TELEFONO");

        tTelefono.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        tTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        eNit.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        eNit.setText("NIT");

        tNit.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        tNit.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        bBuscar.setBackground(new java.awt.Color(204, 204, 204));
        bBuscar.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        bBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bBuscar.png"))); // NOI18N
        bBuscar.setText("BUSCAR");
        bBuscar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        bModificar.setBackground(new java.awt.Color(204, 204, 204));
        bModificar.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        bModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bModificar.png"))); // NOI18N
        bModificar.setText("MODIFICAR");
        bModificar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        bBinario.setBackground(new java.awt.Color(204, 204, 204));
        bBinario.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        bBinario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bBinario.png"))); // NOI18N
        bBinario.setText("BINARIO");
        bBinario.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        bBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBinarioActionPerformed(evt);
            }
        });

        bAgregar.setBackground(new java.awt.Color(204, 204, 204));
        bAgregar.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        bAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bAgregar.png"))); // NOI18N
        bAgregar.setText("AGREGAR");
        bAgregar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });

        bEliminar.setBackground(new java.awt.Color(204, 204, 204));
        bEliminar.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        bEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bEliminar.png"))); // NOI18N
        bEliminar.setText("ELIMINAR");
        bEliminar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        bReporte.setBackground(new java.awt.Color(204, 204, 204));
        bReporte.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        bReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bReporte.png"))); // NOI18N
        bReporte.setText("REPORTE");
        bReporte.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        bReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(eCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tCodigo)
                            .addComponent(eCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(eNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(eTelefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(eNit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tNit, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eHuespedT)
                        .addGap(48, 48, 48)
                        .addComponent(eHuesped)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eHuespedT)
                            .addComponent(eHuesped))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eNombre)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eCodigo))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eCorreo)
                    .addComponent(tCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eNit)
                    .addComponent(tNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bBuscar)
                        .addComponent(bEliminar))
                    .addComponent(bAgregar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bBinario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bReporte)
                        .addComponent(bModificar)))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalir2ActionPerformed
         vMenu abrir= new  vMenu();
        abrir.setVisible(true);
         dispose();
    }//GEN-LAST:event_bSalir2ActionPerformed

    private Huesped buscarCodigo(String codigo)
    {
        boolean encontrado =false; // bandera: no se ha encontrado nit
        Iterator <Huesped> it = Hu.iterator();
            Huesped huesped = null;
            while(it.hasNext() && (!encontrado)){
            huesped = it.next();
            if(codigo.compareTo(huesped.getCodigo())==0)
            {
            //encontro el nit en el arreglo
                encontrado=true; // cambio de la bandera
            }
                  
            }
        if (encontrado)
        {
        return huesped;
        }
        else
        {
        return null;
        }  
    }
    
    private Huesped buscarNombre(String nombre)
    {
        boolean encontrado =false; // bandera: no se ha encontrado nit
        Iterator <Huesped> it = Hu.iterator();
            Huesped huesped = null;
            while(it.hasNext() && (!encontrado)){
            huesped = it.next();
            if(nombre.compareTo(huesped.getNombre())==0)
            {
            //encontro el nit en el arreglo
                encontrado=true; // cambio de la bandera
            }
                  
            }
        if (encontrado)
        {
        return huesped;
        }
        else
        {
        return null;
        }  
    }
    
    
    
    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        Huesped oHuesped = buscarCodigo(tCodigo.getText());
        if(oHuesped!=null){
        tNombre.setText(oHuesped.getNombre());
        tCorreo.setText(oHuesped.getCorreo());
        tTelefono.setText(oHuesped.getTelefono());
        tNit.setText(oHuesped.getNit());
        }
        else
        {
            JOptionPane.showMessageDialog(null,"**LO SENTIMOS..... EL HUESPED NO EXISTE, INTENTE NUEVAMENTE**", "MENSAJE",JOptionPane.ERROR_MESSAGE);
             LimpiarCampos();
        }
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        Huesped oHuesped = buscarCodigo(tCodigo.getText());
        if(oHuesped!=null)
        {
        oHuesped.setCodigo(tCodigo.getText());
        oHuesped.setNombre(tNombre.getText());
        oHuesped.setCorreo(tCorreo.getText());
        oHuesped.setTelefono(tTelefono.getText());
        oHuesped.setNit(tNit.getText());
        LimpiarCampos();
         JOptionPane.showMessageDialog(null,"**DATOS HAN SIDO MODIFICADOS EXITOSAMENTE**", "MENSAJE",JOptionPane.INFORMATION_MESSAGE);    
        }
        else
        {
        JOptionPane.showMessageDialog(null,"**EL HUESPED NO EXISTE, INTENTA NUEVAMENTE**", "MENSAJE",JOptionPane.ERROR_MESSAGE);
        LimpiarCampos();
        }
    }//GEN-LAST:event_bModificarActionPerformed

    private void LeerBinarioHuesped()
      {
        FileInputStream fis = null;
        ObjectInputStream entrada = null;

        try {

            fis = new FileInputStream("BINARIO HUESPED.dat");
            entrada = new ObjectInputStream(fis);
            Hu = (ArrayList<Huesped>) entrada.readObject(); //es necesario el casting
            
        } catch (FileNotFoundException e) {
                // System.out.println(e.getMessage());
        } catch (ClassNotFoundException e) {
                // System.out.println(e.getMessage());
        } catch (IOException e) {
                // System.out.println(e.getMessage());
        } finally {
            try {
                if (fis != null) {
                    fis.close();
                }
                if (entrada != null) {
                    entrada.close();
                }
            } catch (IOException e) {
                    // System.out.println(e.getMessage());
            }
        }
    }
    
    
    
    
    private void bBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBinarioActionPerformed
         FileOutputStream fos = null;
        ObjectOutputStream salida;
        salida= null;
       

        try {
            //Se crea el fichero
            fos = new FileOutputStream("BINARIO HUESPED.dat");                                                 
            salida = new ObjectOutputStream(fos);
   
            salida.writeObject(Hu);
   
           
        } catch (FileNotFoundException e) {
                 System.out.println("1"+e.getMessage());                                                          
        } catch (IOException e) {
                 System.out.println("2"+e.getMessage());
        } finally {
            try {
                if(fos!=null){
                   fos.close();
                }
                if(salida!=null){
                   salida.close();
                }
            } catch (IOException e) {
                     System.out.println("3"+e.getMessage());
            }
        }   
       
        JOptionPane.showMessageDialog(null,"**SE HA GENERADO EL DOCUMENTO BINARIO EXITOSAMENTE**", "MENSAJE",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bBinarioActionPerformed

    private void LimpiarCampos(){
    tCodigo.setText("");
    tNombre.setText("");
    tCorreo.setText("");
    tTelefono.setText("");
    tNit.setText("");
    
    tCodigo.requestFocus();
    }
    
    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        Huesped tmpHuesped= buscarCodigo(tCodigo.getText());
        if(tmpHuesped==null)
        {// SI NO EXISTE EL CODIGO EN EL ARREGLO DE OBJETOS
         tmpHuesped= buscarNombre(tNombre.getText());
        if(tmpHuesped==null)
        {
         Huesped oHuesped= new Huesped();
        oHuesped.setCodigo(tCodigo.getText());
        oHuesped.setNombre(tNombre.getText());
        oHuesped.setCorreo(tCorreo.getText());
        oHuesped.setTelefono(tTelefono.getText());
        oHuesped.setNit(tNit.getText());
        
        Hu.add(oHuesped);
        JOptionPane.showMessageDialog(null,"**LOS DATOS HAN SIDO AGREGADOS EXITOSAMENTE**", "MENSAJE",JOptionPane.INFORMATION_MESSAGE);
        LimpiarCampos();
        }
        else
        {
              JOptionPane.showMessageDialog(null,"**LO SENTIMOS NOMBRE YA FUE REGISTRADO ANTERIORMENTE**", "ADVERTENCIA",JOptionPane.ERROR_MESSAGE);
                 LimpiarCampos();  
        }
        
        }
        else
        {
        JOptionPane.showMessageDialog(null,"**LO SENTIMOS CODIGO YA FUE REGISTRADO ANTERIORMENTE**", "ADVERTENCIA",JOptionPane.ERROR_MESSAGE);
                 LimpiarCampos(); 
        
        }
  
    }//GEN-LAST:event_bAgregarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        Huesped oHuesped = buscarCodigo(tCodigo.getText());
        if(oHuesped!=null)
        {
        Hu.remove(oHuesped);
        JOptionPane.showMessageDialog(null,"**EL REGISTRO DEL ESTE HUESPED HA SIDO ELIMINIDO CON EXITO**", "MENSAJE",JOptionPane.ERROR_MESSAGE);
        LimpiarCampos();
        }
        else
           {
               JOptionPane.showMessageDialog(null,"**LO SENTIMOS..... HUESPED INEXISTENTE, INTENTE NUEVAMENTE**", "MENSAJE",JOptionPane.ERROR_MESSAGE);
               LimpiarCampos();
           } 
            
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReporteActionPerformed
            BufferedWriter ficheroSalida;
            try {
            ficheroSalida = new BufferedWriter(new FileWriter(new File("REPORTE HUESPED.html")));
            ficheroSalida.write("<HTML><HEAD><TITLE>REPORTE HUESPED</TITLE></HEAD><BODY>");
            ficheroSalida.write("<center><h1>***REPORTE HUESPED**</h1></center>");
            ficheroSalida.write("<center><table border =\"4\">");
            ficheroSalida.write("<tr><th>CODIGO</th><th>NOMBRE</th><th>CORREO</th><th>TELEFONO</th><th>NIT</th></tr>");
            
            Iterator <Huesped> it = Hu.iterator();
            while(it.hasNext()) {
                Huesped h = it.next();
                ficheroSalida.write("<tr><td>"+h.getCodigo()+"</td><td>"+h.getNombre()+"</td><td>"+h.getCorreo()+"</td><td>"+h.getTelefono()+"</td><td>"+h.getNit()+"</td></tr>");
            }
            ficheroSalida.write("</table></center></BODY></HTML>");
            ficheroSalida.close(); //cierra el fichreo
             } catch (IOException ex) {
           
        }
        JOptionPane.showMessageDialog(null,"**SE HA GENERADO TU REPORTE HTML EXITOSAMENTE**", "MENSAJE",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bReporteActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bBinario;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton bReporte;
    private javax.swing.JButton bSalir2;
    private javax.swing.JLabel eCodigo;
    private javax.swing.JLabel eCorreo;
    private javax.swing.JLabel eHuesped;
    private javax.swing.JLabel eHuespedT;
    private javax.swing.JLabel eNit;
    private javax.swing.JLabel eNombre;
    private javax.swing.JLabel eTelefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tCodigo;
    private javax.swing.JTextField tCorreo;
    private javax.swing.JTextField tNit;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tTelefono;
    // End of variables declaration//GEN-END:variables
}
