
package Ventanas;

import Clases.*;
import java.util.ArrayList;



public class vMenu extends javax.swing.JFrame {

    ArrayList<Habitacion> AHb;
    ArrayList<Huesped> AH;
    ArrayList<Reserva> AR;

    
    public vMenu() {
        AHb = new ArrayList<Habitacion>();
        AH =  new ArrayList<Huesped>();
        AR =  new ArrayList<Reserva>();       
       
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eLogo = new javax.swing.JLabel();
        bHuesped = new javax.swing.JButton();
        bHabitacion = new javax.swing.JButton();
        bReservacion = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        eLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.PNG"))); // NOI18N
        eLogo.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        bHuesped.setBackground(new java.awt.Color(204, 204, 204));
        bHuesped.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        bHuesped.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGOBOTON.png"))); // NOI18N
        bHuesped.setText("HUESPEDES");
        bHuesped.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 2, 3, 2, new java.awt.Color(0, 0, 0)));
        bHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHuespedActionPerformed(evt);
            }
        });

        bHabitacion.setBackground(new java.awt.Color(204, 204, 204));
        bHabitacion.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        bHabitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGOFF.png"))); // NOI18N
        bHabitacion.setText("HABITACIONES");
        bHabitacion.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 2, 3, 2, new java.awt.Color(0, 0, 0)));
        bHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHabitacionActionPerformed(evt);
            }
        });

        bReservacion.setBackground(new java.awt.Color(204, 204, 204));
        bReservacion.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        bReservacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LRP.png"))); // NOI18N
        bReservacion.setText("RESERVACIONES");
        bReservacion.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 2, 3, 2, new java.awt.Color(0, 0, 0)));
        bReservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReservacionActionPerformed(evt);
            }
        });

        bSalir.setBackground(new java.awt.Color(204, 204, 204));
        bSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SALIR.png"))); // NOI18N
        bSalir.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bReservacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bHabitacion)
                        .addGap(18, 18, 18)
                        .addComponent(bReservacion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHabitacionActionPerformed
        vHabitacion abrir= new  vHabitacion(AHb);
        abrir.setVisible(true);
         dispose();
    }//GEN-LAST:event_bHabitacionActionPerformed

    private void bHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHuespedActionPerformed
        vHuesped abrir= new  vHuesped(AH);
        abrir.setVisible(true);
         dispose();
    }//GEN-LAST:event_bHuespedActionPerformed

    private void bReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReservacionActionPerformed
        vReserva abrir= new vReserva(AR,AH,AHb);
        abrir.setVisible(true);
         dispose();
    }//GEN-LAST:event_bReservacionActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        dispose();
    }//GEN-LAST:event_bSalirActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHabitacion;
    private javax.swing.JButton bHuesped;
    private javax.swing.JButton bReservacion;
    private javax.swing.JButton bSalir;
    private javax.swing.JLabel eLogo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
