
package Ventanas;


import Clases.*;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




public class vReserva extends javax.swing.JFrame {
    
      ArrayList <Reserva> R;
      ArrayList <Huesped> Hu;
      ArrayList <Habitacion> H;
    
    
    public vReserva(ArrayList<Reserva>AR,ArrayList<Huesped>AHu,ArrayList<Habitacion>AH){
        R=AR;
        Hu=AHu;
        H=AH;
        initComponents();
        LeerBinarioReserva();
        setResizable(false);
        setLocationRelativeTo(null);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eReservaT = new javax.swing.JLabel();
        eRL = new javax.swing.JLabel();
        bSalir2 = new javax.swing.JButton();
        eCorrelativo = new javax.swing.JLabel();
        tCorrelativo = new javax.swing.JTextField();
        eHuesped = new javax.swing.JLabel();
        tHuesped = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tHabitacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tFH = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bVerCliente = new javax.swing.JButton();
        bVerHabitacion = new javax.swing.JButton();
        bBinario = new javax.swing.JButton();
        bAgregar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bReporte = new javax.swing.JButton();
        bBuscar = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        bLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        eReservaT.setFont(new java.awt.Font("Bahnschrift", 1, 45)); // NOI18N
        eReservaT.setText("RESERVACIONES");

        eRL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LR.png"))); // NOI18N

        bSalir2.setBackground(new java.awt.Color(204, 204, 204));
        bSalir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SALIR.png"))); // NOI18N
        bSalir2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        bSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalir2ActionPerformed(evt);
            }
        });

        eCorrelativo.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        eCorrelativo.setText("CORRELATIVO");

        tCorrelativo.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        tCorrelativo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        eHuesped.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        eHuesped.setText("HUESPED");

        tHuesped.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        tHuesped.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel3.setText("HABITACION");

        tHabitacion.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        tHabitacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel4.setText("FECHA/HORA");

        tFH.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        tFH.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTable2.setBackground(new java.awt.Color(204, 204, 204));
        jTable2.setBorder(new javax.swing.border.MatteBorder(null));
        jTable2.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HUESPEDES"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setBorder(new javax.swing.border.MatteBorder(null));
        jTable1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HABITACIONES"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        bVerCliente.setBackground(new java.awt.Color(204, 204, 204));
        bVerCliente.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        bVerCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGOBOTON.png"))); // NOI18N
        bVerCliente.setText("VER HUESPEDES");
        bVerCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerClienteActionPerformed(evt);
            }
        });

        bVerHabitacion.setBackground(new java.awt.Color(204, 204, 204));
        bVerHabitacion.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        bVerHabitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGOFF.png"))); // NOI18N
        bVerHabitacion.setText("VER HABITACIONES");
        bVerHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerHabitacionActionPerformed(evt);
            }
        });

        bBinario.setBackground(new java.awt.Color(204, 204, 204));
        bBinario.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        bBinario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bBinario.png"))); // NOI18N
        bBinario.setText("BINARIO");
        bBinario.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        bBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBinarioActionPerformed(evt);
            }
        });

        bAgregar.setBackground(new java.awt.Color(204, 204, 204));
        bAgregar.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        bAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bAgregar.png"))); // NOI18N
        bAgregar.setText("AGREGAR");
        bAgregar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });

        bEliminar.setBackground(new java.awt.Color(204, 204, 204));
        bEliminar.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        bEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bEliminar.png"))); // NOI18N
        bEliminar.setText("ELIMINAR");
        bEliminar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        bReporte.setBackground(new java.awt.Color(204, 204, 204));
        bReporte.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        bReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bReporte.png"))); // NOI18N
        bReporte.setText("REPORTE");
        bReporte.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        bReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReporteActionPerformed(evt);
            }
        });

        bBuscar.setBackground(new java.awt.Color(204, 204, 204));
        bBuscar.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        bBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bBuscar.png"))); // NOI18N
        bBuscar.setText("BUSCAR");
        bBuscar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        bModificar.setBackground(new java.awt.Color(204, 204, 204));
        bModificar.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        bModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bModificar.png"))); // NOI18N
        bModificar.setText("MODIFICAR");
        bModificar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        bLimpiar.setBackground(new java.awt.Color(204, 204, 204));
        bLimpiar.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        bLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clear.png"))); // NOI18N
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(bEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(bAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(eHuesped)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(eCorrelativo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tCorrelativo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tFH, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(bBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(bVerCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bLimpiar)
                        .addGap(102, 102, 102))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(bVerHabitacion, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(eRL)
                .addGap(68, 68, 68)
                .addComponent(eReservaT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(eRL, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tCorrelativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eCorrelativo))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eHuesped)
                            .addComponent(tHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tFH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eReservaT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bBuscar)
                            .addComponent(bAgregar))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bEliminar)
                            .addComponent(bReporte))
                        .addGap(11, 11, 11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bVerCliente)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bVerHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(bBinario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bModificar, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalir2ActionPerformed
        vMenu abrir= new  vMenu();
        abrir.setVisible(true);
         dispose();
    }//GEN-LAST:event_bSalir2ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int f = this.jTable2.getSelectedRow();
        tHuesped.setText(this.jTable2.getValueAt(f,0).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int f = this.jTable1.getSelectedRow();
        tHabitacion.setText(this.jTable1.getValueAt(f,0).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void bVerClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerClienteActionPerformed
         File archivo = new File("BINARIO HUESPED.dat");
       try{
           DefaultTableModel dtm = (DefaultTableModel) this.jTable2.getModel();
           
       FileInputStream fis = null;
       ObjectInputStream entrada = null;
       FileWriter filewriter = null;
       PrintWriter printw = null;
       fis = new FileInputStream(archivo);
       entrada= new ObjectInputStream(fis);
       Hu = (ArrayList<Huesped>) entrada.readObject();
        Huesped u = new Huesped();
       for (Huesped usuarios: Hu){
       String nombre = usuarios.getNombre();
       Object data[] = {nombre};
       dtm.addRow(data);

       }
 

       }catch (Exception e){

       }
    }//GEN-LAST:event_bVerClienteActionPerformed

    private void bVerHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerHabitacionActionPerformed
             File archivo = new File("BINARIO HABITACION.dat");
       try{
           DefaultTableModel dtm = (DefaultTableModel) this.jTable1.getModel();
           
       FileInputStream fis = null;
       ObjectInputStream entrada = null;
       FileWriter filewriter = null;
       PrintWriter printw = null;
       fis = new FileInputStream(archivo);
       entrada= new ObjectInputStream(fis);
       H = (ArrayList<Habitacion>) entrada.readObject();
        Habitacion u = new Habitacion();
       for (Habitacion usuarios: H){
       String nombre = usuarios.getNombre();
       Object data[] = {nombre};
       dtm.addRow(data);

       }

       }catch (Exception e){
       
       }
    }//GEN-LAST:event_bVerHabitacionActionPerformed

    
   private void LeerBinarioReserva()
      {
        FileInputStream fis = null;
        ObjectInputStream entrada = null;

        try {

            fis = new FileInputStream("BINARIO RESERVA.dat");
            entrada = new ObjectInputStream(fis);
            R = (ArrayList<Reserva>) entrada.readObject(); //es necesario el casting
            
        } catch (FileNotFoundException e) {
                // System.out.println(e.getMessage());
        } catch (ClassNotFoundException e) {
                // System.out.println(e.getMessage());
        } catch (IOException e) {
                // System.out.println(e.getMessage());
        } finally {
            try {
                if (fis != null) {
                    fis.close();
                }
                if (entrada != null) {
                    entrada.close();
                }
            } catch (IOException e) {
                    // System.out.println(e.getMessage());
            }
        }
    }
    
    private void bBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBinarioActionPerformed
         FileOutputStream fos = null;
        ObjectOutputStream salida;
        salida= null;
       

        try {
            //Se crea el fichero
            fos = new FileOutputStream("BINARIO RESERVA.dat");                                                 
            salida = new ObjectOutputStream(fos);
   
            salida.writeObject(R);
   
           
        } catch (FileNotFoundException e) {
                 System.out.println("1"+e.getMessage());                                                          
        } catch (IOException e) {
                 System.out.println("2"+e.getMessage());
        } finally {
            try {
                if(fos!=null){
                   fos.close();
                }
                if(salida!=null){
                   salida.close();
                }
            } catch (IOException e) {
                     System.out.println("3"+e.getMessage());
            }
        }   
       
        JOptionPane.showMessageDialog(null,"**SE HA GENERADO EL DOCUMENTO BINARIO EXITOSAMENTE**", "MENSAJE",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bBinarioActionPerformed

    private void LimpiarCampos(){
    tCorrelativo.setText("");
    tHuesped.setText("");
    tHabitacion.setText("");
    tFH.setText("");
    
    tCorrelativo.requestFocus();
    
    }
    
    
    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        Reserva tmpReserva= buscarCorrelativo(tCorrelativo.getText());
        if(tmpReserva==null){
            
            Reserva oReserva = new Reserva();
            oReserva.setCorrelativo(tCorrelativo.getText());
            oReserva.setHuesped(tHuesped.getText());
            oReserva.setHabitacion(tHabitacion.getText());
            oReserva.setFechaHora(tFH.getText());
            
            R.add(oReserva);
            
            JOptionPane.showMessageDialog(null,"**LOS DATOS HAN SIDO AGREGADOS EXITOSAMENTE**", "MENSAJE",JOptionPane.INFORMATION_MESSAGE);
            LimpiarCampos();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"**LO SENTIMOS CORRELATIVO  YA FUE REGISTRADO ANTERIORMENTE**", "ADVERTENCIA",JOptionPane.ERROR_MESSAGE);
                 LimpiarCampos(); 
        
        }
            
            
    }//GEN-LAST:event_bAgregarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        Reserva oReserva = buscarCorrelativo(tCorrelativo.getText());
        if(oReserva!=null){
        
        R.remove(oReserva);
        JOptionPane.showMessageDialog(null,"**EL REGISTRO DE LA HABITACION HA SIDO ELIMINIDO CON EXITO**", "MENSAJE",JOptionPane.ERROR_MESSAGE);
        LimpiarCampos();
        }
          else
           {
               JOptionPane.showMessageDialog(null,"**LO SENTIMOS..... RESERVACION INEXISTENTE, INTENTE NUEVAMENTE**", "MENSAJE",JOptionPane.ERROR_MESSAGE);
               LimpiarCampos();
           }   
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReporteActionPerformed
        BufferedWriter ficheroSalida;
            try {
            ficheroSalida = new BufferedWriter(new FileWriter(new File("REPORTE RESERVACION.html")));
            ficheroSalida.write("<HTML><HEAD><TITLE>REPORTE RESERVACION</TITLE></HEAD><BODY>");
            ficheroSalida.write("<center><h1>***REPORTE RESERVACION**</h1></center>");
            ficheroSalida.write("<center><table border =\"4\">");
            ficheroSalida.write("<tr><th>CORRELATIVO</th><th>HUESPED</th><th>HABITACION</th><th>FECHA Y HORA</th></tr>");
            
            Iterator <Reserva> it = R.iterator();
            while(it.hasNext()) {
                Reserva r = it.next();
                ficheroSalida.write("<tr><td>"+r.getCorrelativo()+"</td><td>"+r.getHuesped()+"</td><td>"+r.getHabitacion()+"</td><td>"+r.getFechaHora()+"</td></tr>");
            }
            ficheroSalida.write("</table></center></BODY></HTML>");
            ficheroSalida.close(); //cierra el fichreo
             } catch (IOException ex) {
           
        }
        JOptionPane.showMessageDialog(null,"**SE HA GENERADO TU REPORTE HTML EXITOSAMENTE**", "MENSAJE",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bReporteActionPerformed

    private Reserva buscarCorrelativo(String correlativo)
    {
        boolean encontrado =false; // bandera: no se ha encontrado nit
        Iterator <Reserva> it = R.iterator();
            Reserva reserva = null;
            while(it.hasNext() && (!encontrado)){
            reserva = it.next();
            if(correlativo.compareTo(reserva.getCorrelativo())==0)
            {
            //encontro el nit en el arreglo
                encontrado=true; // cambio de la bandera
            }
                  
            }
        if (encontrado)
        {
        return reserva;
        }
        else
        {
        return null;
        }  
    }
    
    
    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
            Reserva oReserva = buscarCorrelativo(tCorrelativo.getText());
        if(oReserva!=null){
        tHuesped.setText(oReserva.getHuesped());
        tHabitacion.setText(oReserva.getHabitacion());
        tFH.setText(oReserva.getFechaHora());
        
       
        }
        else
        {
            JOptionPane.showMessageDialog(null,"**LO SENTIMOS..... LA RESERVACION NO EXISTE, INTENTE NUEVAMENTE**", "MENSAJE",JOptionPane.ERROR_MESSAGE);
             LimpiarCampos();
        }
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
         Reserva oReserva = buscarCorrelativo(tCorrelativo.getText());
        if(oReserva!=null){
            oReserva.setCorrelativo(tCorrelativo.getText());
            oReserva.setHuesped(tHuesped.getText());
            oReserva.setHabitacion(tHabitacion.getText());
            oReserva.setFechaHora(tFH.getText());

            JOptionPane.showMessageDialog(null,"**LOS DATOS HAN SIDO AGREGADOS EXITOSAMENTE**", "MENSAJE",JOptionPane.INFORMATION_MESSAGE);
            LimpiarCampos();
        }
        else
        {
        JOptionPane.showMessageDialog(null,"**LA RESERVACION NO EXISTE, INTENTA NUEVAMENTE**", "MENSAJE",JOptionPane.ERROR_MESSAGE);
        LimpiarCampos();
        }
    }//GEN-LAST:event_bModificarActionPerformed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bBinario;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton bReporte;
    private javax.swing.JButton bSalir2;
    private javax.swing.JButton bVerCliente;
    private javax.swing.JButton bVerHabitacion;
    private javax.swing.JLabel eCorrelativo;
    private javax.swing.JLabel eHuesped;
    private javax.swing.JLabel eRL;
    private javax.swing.JLabel eReservaT;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField tCorrelativo;
    private javax.swing.JTextField tFH;
    private javax.swing.JTextField tHabitacion;
    private javax.swing.JTextField tHuesped;
    // End of variables declaration//GEN-END:variables
}
